name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, selfish World!"
      - name: Run a multi-line script
        run: |
          echo "node.js version: $(node -v)"
          echo "npm version: $(npm -v)"
         